md app
md src
md dist
md build
md app\config
md app\controllers
md app\db
md app\logs
md app\views
md app\routes
md app\models
md app\middleware
md app\certs
md src\js
md src\scss
md src\assets
md src\assets\img
md public
md dist\public
md dist\public\img
md dist\public\js
md dist\public\css
md dist\app\config
md dist\app\controllers
md dist\app\db
md dist\app\logs
md dist\app\views
md dist\app\routes
md dist\app\models
md dist\app\middleware
md dist\app\certs

